# Generated by Django 5.2.7 on 2026-04-16 01:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hngwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('gender', models.CharField(max_length=20)),
                ('gender_probability', models.FloatField()),
                ('gender_size', models.IntegerField()),
                ('age', models.IntegerField()),
                ('age_group', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('country_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
