# Generated by Django 5.2.7 on 2026-04-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hngwork', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender_size',
            new_name='sample_size',
        ),
    ]
